fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

