# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider:     fos_userbundle
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
                remember_me:  true
                always_use_default_target_path : true
                default_target_path: /profile
                use_referer : true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fos_user_security_logout
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, roles: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }